package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
      com.pichillilorenzo.flutter_appavailability.AppAvailability.registerWith(shimPluginRegistry.registrarFor("com.pichillilorenzo.flutter_appavailability.AppAvailability"));
      io.github.itzmeanjan.intent.IntentPlugin.registerWith(shimPluginRegistry.registrarFor("io.github.itzmeanjan.intent.IntentPlugin"));
    flutterEngine.getPlugins().add(new com.lyokone.location.LocationPlugin());
      flutter.moum.open_appstore.OpenAppstorePlugin.registerWith(shimPluginRegistry.registrarFor("flutter.moum.open_appstore.OpenAppstorePlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());
  }
}
